#!/usr/bin/env node
// Copies the ABI section out of each compiled artifact and writes it as
// a typed `as const` TS module under frontend/src/contracts/abis/.
// Wired into `npm run compile` so the frontend always has fresh ABIs.

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const ARTIFACTS = path.join(ROOT, "artifacts", "contracts");
const OUT_DIR = path.join(ROOT, "frontend", "src", "contracts", "abis");

// (artifact source path, output filename, exported const name).
// We deliberately re-export MockWETH as WETH so the frontend can target the
// canonical Sepolia WETH (its on-chain ABI is a superset of MockWETH's).
const TARGETS = [
    {
        from: "v2-core/UniswapV2Factory.sol/UniswapV2Factory.json",
        out: "UniswapV2Factory.ts",
        name: "UNISWAP_V2_FACTORY_ABI",
    },
    {
        from: "v2-core/UniswapV2Pair.sol/UniswapV2Pair.json",
        out: "UniswapV2Pair.ts",
        name: "UNISWAP_V2_PAIR_ABI",
    },
    {
        from: "v2-periphery/UniswapV2Router.sol/UniswapV2Router.json",
        out: "UniswapV2Router.ts",
        name: "UNISWAP_V2_ROUTER_ABI",
    },
    {
        from: "mocks/TestERC20.sol/TestERC20.json",
        out: "TestERC20.ts",
        name: "TEST_ERC20_ABI",
    },
    {
        from: "erc20.sol/SibeiCoin.json",
        out: "SibeiCoin.ts",
        name: "SIBEICOIN_ABI",
    },
    {
        from: "MockWETH.sol/MockWETH.json",
        out: "WETH.ts",
        name: "WETH_ABI",
    },
];

function main() {
    if (!fs.existsSync(ARTIFACTS)) {
        console.error(
            `No artifacts directory at ${ARTIFACTS}. Run \`npx hardhat compile\` first.`,
        );
        process.exit(1);
    }
    fs.mkdirSync(OUT_DIR, { recursive: true });

    const header = "// AUTO-GENERATED by scripts/copy-abis.js — do not edit by hand.\n";

    for (const t of TARGETS) {
        const fromPath = path.join(ARTIFACTS, t.from);
        if (!fs.existsSync(fromPath)) {
            console.warn(`  skip: ${t.from} not found`);
            continue;
        }
        const artifact = JSON.parse(fs.readFileSync(fromPath, "utf8"));
        const abiJson = JSON.stringify(artifact.abi, null, 4);
        const body = `${header}\nexport const ${t.name} = ${abiJson} as const;\n`;
        const outPath = path.join(OUT_DIR, t.out);
        fs.writeFileSync(outPath, body);
        console.log(`  wrote ${path.relative(ROOT, outPath)}`);
    }
}

main();
